# -*- coding: utf-8 -*-
"""Financial Distress Early‑Warning System for U.S. Companies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KV7ytFtuG3RfexrJV07CvxV5YyOihxXN
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/corporateCreditRatingWithFinancialRatios.csv'
df_raw = pd.read_csv(file_path)
display(df_raw.head())

df=df_raw

df.shape

df.isnull().sum()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df.head()
df.info()
df.describe()

df.columns

df['Binary Rating'].value_counts()

df['Binary Rating'].value_counts(normalize=True)

import pandas as pd
import numpy as np

# Use Binary Rating as target
df['is_distressed'] = df['Binary Rating']

# Define feature columns
features = [
    'Current Ratio',
    'Long-term Debt / Capital',
    'Debt/Equity Ratio',
    'Gross Margin',
    'Operating Margin',
    'EBIT Margin',
    'EBITDA Margin',
    'Pre-Tax Profit Margin',
    'Net Profit Margin',
    'Asset Turnover',
    'ROE - Return On Equity',
    'Return On Tangible Equity',
    'ROA - Return On Assets',
    'ROI - Return On Investment',
    'Operating Cash Flow Per Share',
    'Free Cash Flow Per Share'
]

df.isna().sum().sort_values(ascending=False)

df['Binary Rating'].value_counts(normalize=True)

sns.countplot(data=df, x='Binary Rating')
plt.title("Distribution of Distressed vs Healthy Companies")
plt.show()

numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns

corr = df[numeric_cols].corr()

plt.figure(figsize=(14,10))
sns.heatmap(corr, cmap='coolwarm', center=0)
plt.title("Correlation Heatmap of Financial Ratios")
plt.show()

key_ratios = [
    'Current Ratio',
    'Debt/Equity Ratio',
    'Gross Margin',
    'Net Profit Margin',
    'ROA - Return On Assets',
    'ROE - Return On Equity'
]

for col in key_ratios:
    plt.figure(figsize=(6,4))
    sns.boxplot(data=df, x='Binary Rating', y=col)
    plt.title(f"{col} by Distress Class")
    plt.show()

df[key_ratios].describe(percentiles=[0.01, 0.05, 0.95, 0.99]).T

df.to_csv("cleaned_financial_ratios.csv", index=False)

df.isna().sum().sort_values(ascending=False)

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data=df, x='Binary Rating')
plt.title("Distribution of Distressed vs Healthy Companies")
plt.xlabel("Binary Rating (1 = Distressed, 0 = Healthy)")
plt.ylabel("Count")
plt.show()

df.describe().T

numeric_cols = [
    'Current Ratio',
    'Long-term Debt / Capital',
    'Debt/Equity Ratio',
    'Gross Margin',
    'Operating Margin',
    'EBIT Margin',
    'EBITDA Margin',
    'Pre-Tax Profit Margin',
    'Net Profit Margin',
    'Asset Turnover',
    'ROE - Return On Equity',
    'Return On Tangible Equity',
    'ROA - Return On Assets',
    'ROI - Return On Investment',
    'Operating Cash Flow Per Share',
    'Free Cash Flow Per Share'
]

corr = df[numeric_cols].corr()

plt.figure(figsize=(14,10))
sns.heatmap(corr, cmap='coolwarm', center=0, annot=False)
plt.title("Correlation Heatmap of Financial Ratios")
plt.show()

key_ratios = [
    'Current Ratio',
    'Debt/Equity Ratio',
    'Gross Margin',
    'Net Profit Margin',
    'ROA - Return On Assets',
    'ROE - Return On Equity'
]

for col in key_ratios:
    plt.figure(figsize=(6,4))
    sns.boxplot(data=df, x='Binary Rating', y=col)
    plt.title(f"{col} by Distress Class")
    plt.show()

key_ratios = [
    'Current Ratio',
    'Debt/Equity Ratio',
    'Gross Margin',
    'Net Profit Margin',
    'ROA - Return On Assets',
    'ROE - Return On Equity'
]

df[key_ratios].describe(percentiles=[0.01, 0.05, 0.95, 0.99]).T

"""The dataset contains extreme outliers in several financial ratios.  
Not missing values — but very large, very negative, or unrealistic values that can distort models

* ## Debt/Equity Ratio:

Mean: 0.17

Std: 34.45

Min: –1473

99th percentile: 26

Max: 194

This means:

    Some companies have negative equity (common in distress)

    Some ratios explode to huge magnitudes

    These values will break Logistic Regression and distort scaling

➡️ We must clip or winsorize this feature.


* ## ROE

This is the most extreme:

    Min: –11,258%

    Max: 7,038%

    Std: 230 (huge)
    ➡️ ROE explodes when equity is near zero — very common.

➡️ We must clip ROE.
"""

ratio_cols = [
    'Current Ratio',
    'Debt/Equity Ratio',
    'Gross Margin',
    'Net Profit Margin',
    'ROA - Return On Assets',
    'ROE - Return On Equity'
]

for col in ratio_cols:
    lower = df[col].quantile(0.01)
    upper = df[col].quantile(0.99)
    df[col] = df[col].clip(lower, upper)

df[ratio_cols].describe(percentiles=[0.01, 0.05, 0.95, 0.99]).T

"""## Feature Selection & Train/Test Split"""

features = [
    'Current Ratio',
    'Long-term Debt / Capital',
    'Debt/Equity Ratio',
    'Gross Margin',
    'Operating Margin',
    'EBIT Margin',
    'EBITDA Margin',
    'Pre-Tax Profit Margin',
    'Net Profit Margin',
    'Asset Turnover',
    'ROE - Return On Equity',
    'Return On Tangible Equity',
    'ROA - Return On Assets',
    'ROI - Return On Investment',
    'Operating Cash Flow Per Share',
    'Free Cash Flow Per Share'
]

df_model = df.copy()

X = df_model[features]
y = df_model['is_distressed']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score

model_lr = LogisticRegression(max_iter=2000)
model_lr.fit(X_train, y_train)

y_pred = model_lr.predict(X_test)
y_proba = model_lr.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_proba))

"""# **Interpretation of the Classification Report**
### Class 1 (Distressed Companies)

    Precision: 0.78

    Recall: 0.93

    F1‑score: 0.85

High recall means we are catching most distressed companies.
High F1 means the model is balanced and reliable.

This is critical because in real credit risk:

    Missing a distressed company is far more costly

    False positives are acceptable

The model is behaving like a real‑world early‑warning system.


### Class 0 (Healthy Companies)

    Precision: 0.78

    Recall: 0.50

    F1‑score: 0.61

This is also expected because the model is biased toward catching distress, which is correct for:

    Credit risk

    Bankruptcy prediction

    Early‑warning systems

    Fraud detection

    Medical risk models

In these domains, recall for the positive class is more important than recall for the negative class
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, classification_report

rf = RandomForestClassifier(
    n_estimators=400,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
rf_proba = rf.predict_proba(X_test)[:, 1]

print(classification_report(y_test, rf_pred))
print("RF ROC-AUC:", roc_auc_score(y_test, rf_proba))

"""The Model's Performance Is Outstanding

Random Forest Results

    Accuracy: 0.91

    ROC‑AUC: 0.968

    F1 (Distressed): 0.93

    Recall (Distressed): 0.94


A ROC‑AUC near 0.97 means:

    The model can almost perfectly separate distressed from healthy companies

    The financial ratios in the dataset have very strong predictive power

    The preprocessing (clipping, cleaning, feature selection) was exactly right


"""

## XGBOOST
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, roc_auc_score

xgb = XGBClassifier(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.9,
    colsample_bytree=0.9,
    eval_metric='logloss',
    random_state=42
)

xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
xgb_proba = xgb.predict_proba(X_test)[:, 1]

print(classification_report(y_test, xgb_pred))
print("XGB ROC-AUC:", roc_auc_score(y_test, xgb_proba))

"""The XGBoost Model Is Nearly Perfect

A ROC‑AUC of 0.964 is exceptional for real‑world financial data.
This means:

    The model can almost perfectly distinguish distressed vs healthy companies

    The feature engineering and clipping strategy were spot‑on

    The dataset has strong predictive signal

    We now have two high‑performing models (RF and XGB) to compare

Random Forest vs XGBoost

Both models are excellent:


Random Forest's ROC‑AUC of	0.968	 is Slightly better separation and very stable.

XGBoost's ROC‑AUC	o 0.964 is	More flexible and better for SHAP explainability.

For this project, we will use XGBoost as the final model because:

    SHAP integrates naturally

    It produces cleaner feature importance

    It’s more widely used in finance and credit modeling

    It’s easier to explain to executives
"""

### SHAP Explainability

import shap

explainer = shap.TreeExplainer(xgb)
shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test)

"""#Interpretation

1. Long‑term Debt / Capital (Top Predictor)

This is the strongest signal of distress.
High leverage → higher financial risk → higher probability of default.

This matches:

    Altman Z‑Score

    Moody’s credit methodology

    S&P corporate rating frameworks

Your model is behaving like a real credit‑risk engine.

🔥 2. ROI (Return on Investment)

Low ROI means:

    Poor capital efficiency

    Weak returns on deployed capital

    Ineffective management decisions

Companies with declining ROI often enter distress before profitability collapses.

🔥 3. Pre‑Tax Profit Margin

This is a powerful early indicator because:

    It reflects operational performance

    It excludes tax distortions

    It shows core profitability

Falling pre‑tax margins often precede:

    Credit downgrades

    Liquidity issues

    Negative earnings

    4. Current Ratio

Liquidity is critical.

Low current ratio → inability to meet short‑term obligations → distress risk.

This is exactly what banks monitor.

🔥 5–7. Gross Margin, Net Profit Margin, EBITDA Margin

These profitability metrics show:

    Pricing power

    Cost control

    Operational efficiency

Declining margins → weakening business fundamentals.

🔥 8–12. ROA, ROE, Return on Tangible Equity, Asset Turnover, Debt/Equity

These ratios capture:

    Asset efficiency

    Shareholder returns

    Capital structure

    Operational productivity

They are secondary but still meaningful.

🔥 13–14. Cash Flow Metrics (OCF/Share, FCF/Share)

Cash flow is important, but in this dataset:

    Ratios may be noisy

    Cash flow per share varies by industry

    Profitability ratios dominate signal

Still useful, but not top drivers.

🔥 15–16. Operating Margin, EBIT Margin

These are correlated with other profitability metrics (Gross Margin, EBITDA Margin), so SHAP ranks them lower.

Tree models naturally down‑rank redundant features.
"""

## Export SHAP + Predictions for Power BI
import pandas as pd

# Create results dataframe
results = X_test.copy()
results['predicted_prob_distress'] = xgb_proba
results['actual_distress'] = y_test.values
results['Corporation'] = df.loc[X_test.index, 'Corporation']
results['Rating'] = df.loc[X_test.index, 'Rating']

# Save for Power BI
results.to_csv("powerbi_model_outputs.csv", index=False)

## Power BI‑friendly dataset.

import pandas as pd

# Create results dataframe
results = X_test.copy()

results['predicted_prob_distress'] = xgb_proba
results['actual_distress'] = y_test.values

# Add identifiers
results['Corporation'] = df.loc[X_test.index, 'Corporation']
results['Rating'] = df.loc[X_test.index, 'Rating']
results['Sector'] = df.loc[X_test.index, 'Sector']
results['Ticker'] = df.loc[X_test.index, 'Ticker']

# Save for Power BI
results.to_csv("powerbi_model_outputs.csv", index=False)

## Exporting SHAP Values for Company‑Level Explainability

shap_df = pd.DataFrame(shap_values, columns=features)
shap_df['Corporation'] = df.loc[X_test.index, 'Corporation']
shap_df['predicted_prob_distress'] = xgb_proba

shap_df.to_csv("powerbi_shap_values.csv", index=False)